---
title: Homepage
startUrl: https://{{ root_host }}
theme: dark
headerStyle: clean
cardBlur: md
color: zinc
fiveColumns: false
layout:
  Monitoring:
    style: row
    columns: 2
  Network & Security:
    style: row
    columns: 2
  Apps:
    style: row
    columns: 3
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: false
