- search:
    provider: custom
    url: https://www.google.com/search?q=
    target: _blank
    focus: false

- greeting:
    text_size: xl
    text: "Server Dashboard"

- resources:
    cpu: true
    memory: true
    disk: /
    expanded: true
    label: System

- openmeteo:
    label: Istanbul
    latitude: 41.0082
    longitude: 28.9784
    timezone: Europe/Istanbul
    units: metric
    cache: 5

- datetime:
    text_size: l
    format:
      dateStyle: long
      timeStyle: short
      hour12: false
