- name: Create prometheus directory
  ansible.builtin.file:
    path: "/etc/prometheus/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Create prometheus.yml file
  ansible.builtin.copy:
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['node_exporter:9100']
        - job_name: 'cadvisor'
          static_configs:
            - targets: ['cadvisor:8080']
        - job_name: 'traefik'
          metrics_path: "/metrics"
          static_configs:
            - targets: ['traefik:8899']
        - job_name: 'crowdsec'
          static_configs:
            - targets: ['crowdsec:6060']
    dest: /etc/prometheus/prometheus.yml
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Create volumes for monitoring containers
  community.docker.docker_volume:
    name: "{{ item }}"
    state: present
    driver: local
  loop:
    - prometheus-data
    - grafana-data

- name: Ensure grafana-data directory exists and has correct permissions
  ansible.builtin.file:
    path: "{{ docker_dir }}/grafana-data"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Create prometheus container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:{{ prometheus_version }}
    pull: "always"
    state: started
    restart_policy: unless-stopped
    volumes:
      - /etc/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    security_opts:
      - no-new-privileges:true
      - apparmor:docker-default
    command: "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - name: prometheus_network

- name: Create node exporter container
  community.docker.docker_container:
    name: node_exporter
    image: quay.io/prometheus/node-exporter:{{ node_exporter_version }}
    pull: "always"
    state: started
    restart_policy: unless-stopped
    user: "1000:1000"
    pid_mode: host
    command: "--path.rootfs=/host"
    security_opts:
      - no-new-privileges:true
      - apparmor:docker-default
    volumes:
      - /:/host:ro,rslave
    networks:
      - name: prometheus_network

- name: Create cadvisor container
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:{{ cadvisor_version }}
    pull: "always"
    state: started
    restart_policy: unless-stopped
    security_opts:
      - no-new-privileges:true
      - apparmor:docker-default
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    networks:
      - name: prometheus_network

- name: Create grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana-oss:{{ grafana_version }}
    pull: "always"
    state: started
    restart_policy: unless-stopped
    user: "1000:1000"
    security_opts:
      - no-new-privileges:true
      - apparmor:docker-default
    volumes:
      - "{{ docker_dir }}/grafana-data:/var/lib/grafana"
    networks:
      - name: dns_network
      - name: prometheus_network
      - name: homepage_network
    labels:
      traefik.enable: "true"
      traefik.docker.network: "dns_network"
      traefik.http.routers.grafana.entrypoints: "https"
      traefik.http.routers.grafana.rule: "Host(`{{ grafana_host }}`)"
      traefik.http.routers.grafana.tls: "true"
      traefik.http.routers.grafana.service: "grafana"
      traefik.http.routers.grafana.middlewares: "secure-vpn-with-auth@file"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
      