username: "ansible"
ansible_host: "192.168.1.1"
root_host: "example.com"
ansible_ssh_private_key_file: "~/.ssh/ansible"
email_recipient: "reciever@gmail.com" #email to receive notifications
email_smtp_host: "smtp.gmail.com" #smtp server
email_smtp_port: "587" #smtp port
email_login: "sender@gmail.com" #email to send notifications
force_recreate: true
immich_storage_box_enabled: false
immich_storage_box_type: "sftp"
immich_storage_box_host: ""
immich_storage_box_port: 22
immich_storage_box_user: ""
immich_storage_box_remote_path: "immich"
immich_storage_box_mount_enabled: false
immich_storage_box_mount_path: "{{ docker_dir }}/immich/external"
immich_upload_location: "{{ docker_dir }}/immich/library"
