email_password: #email password
authelia_password: #authelia password
cloudflare_email: #cloudflare email
cloudflare_api_key: #cloudflare api key
traefik_basic_auth_hash: #htpasswd -nb user traefik_password
traefik_password: #traefik_password
authelia_jwt_secret: #openssl rand -hex 64
authelia_session_secret: #openssl rand -hex 64
authelia_storage_encryption_key: #openssl rand -hex 64
adguard_password_hash: #htpasswd -B -C 10 -n -b admin adguard_password | cut -d':' -f2
adguard_password: #adguard_password
wireguard_password_hash: #htpasswd -nb user wireguard_password | cut -d':' -f2
wireguard_password: #wireguard_password
grafana_password: #grafana_password
watchtower_token: #watchtower token
crowdsecLapiKey: #crowdsec lapi key
crowdsecMachineApiKey: #crowdsec machine api key
ansible_password: #ssh key password
ansible_become_pass: #sudo password
trojan_password: #trojan password
wmess_guid_1: #v2ray guid
wmess_guid_2: #v2ray guid
vless_guid_1: #v2ray guid
telegram_user_id: #telegram user id
telegram_api_token:  #telegram api token
freqtrade_jwt_secret_key: #openssl rand -hex 64
freqtrade_api_password: #freqtrade password
freqtrade_api_username: #freqtrade user
freqtrade_ws_token: #openssl rand -hex 64
binance_exchange_api_key: #binance api key
binance_exchange_api_secret: #binance api secret
kucoin_exchange_api_key: #kucoin api key
kucoin_exchange_api_secret: #kucoin api secret
kucoin_exchange_api_password: #kucoin api password