email_password:
authelia_password:
cloudflare_email:
cloudflare_api_key:
traefik_basic_auth_hash:
jwt_secret:
session_secret:
storage_encryption_key:
adguard_password_hash:
adguard_password:
traefik_password:
wireguard_password_hash:
wireguard_password:
grafana_password:
watchtower_token:
crowdsecLapiKey:
crowdsecMachineApiKey:
ansible_password: 
ansible_become_pass:
trojan_password:
wmess_guid_1:
wmess_guid_2:
vless_guid_1:
telegram_user_id:
telegram_api_token: