---
- name: Make sure Watchtower is created and running
  community.general.docker_container:
    name: "watchtower"
    image: "containrrr/watchtower:{{ watchtower_version }}"
    pull: "always"
    state: started
    restart_policy: unless-stopped
    user: "1000:1000"
    security_opts:
      - no-new-privileges:true
      - apparmor:docker-default
    env:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_HTTP_API_METRICS: "true"
      WATCHTOWER_HTTP_API_TOKEN: "{{ watchtower_token }}"
      WATCHTOWER_MONITOR_ONLY: "true"
      WATCHTOWER_NOTIFICATIONS: "email"
      WATCHTOWER_WARN_ON_HEAD_FAILURE: "never"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "{{ email_login }}"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "{{ email_recipient }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "{{ email_smtp_host }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "{{ email_smtp_port }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "{{ email_login }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "{{ email_password }}"
      DOCKER_HOST: tcp://docker_proxy:2375
    networks:
      - name: public_network
      - name: docker_proxy_network