---
jellyfin_version: "latest"
jellyfin_data_dir: "{{ docker_dir }}/jellyfin"
jellyfin_media_mount_path: "{{ docker_dir }}/jellyfin/media"
jellyfin_storage_box_mount_enabled: true

# Webhook plugin
jellyfin_webhook_plugin_version: "18.0.0.0"
jellyfin_webhook_plugin_url: "https://repo.jellyfin.org/releases/plugin/webhook/webhook_18.0.0.0.zip"
