---
- name: Install AppArmor
  become: true
  ansible.builtin.apt:
    name: apparmor
    state: present
    update_cache: true

- name: Start AppArmor service
  ansible.builtin.service:
    name: apparmor
    state: started
    enabled: true

- name: Install jq
  become: true
  ansible.builtin.apt:
    name: jq
    state: present
    update_cache: true

- name: Remove pam-notification.sh if present
  become: true
  ansible.builtin.file:
    path: /opt/pam-notification.sh
    state: absent

- name: Template the sshd
  become: true
  ansible.builtin.template:
    src: sshd
    dest: /etc/pam.d/sshd
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Remove sudo PAM notification
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sudo
    line: "session    optional     pam_exec.so /opt/sudo-notification.sh"
    state: absent
