---
- name: Install AppArmor
  become: true
  ansible.builtin.apt:
    name: apparmor
    state: present
    update_cache: true

- name: Start AppArmor service
  ansible.builtin.service:
    name: apparmor
    state: started
    enabled: true

- name: Install jq
  become: true
  ansible.builtin.apt:
    name: jq
    state: present
    update_cache: true

- name: Template the pam-notification.sh
  become: true
  ansible.builtin.template:
    src: pam-notification.sh
    dest: /opt/pam-notification.sh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Template the sshd
  become: true
  ansible.builtin.template:
    src: sshd
    dest: /etc/pam.d/sshd
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
