---
- name: Create the n8n directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/n8n"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0775"

- name: Make sure the n8n container is created and running
  community.general.docker_container:
    name: "n8n"
    image: "docker.n8n.io/n8nio/n8n:{{ n8n_version }}"
    pull: "always"
    state: started
    restart_policy: unless-stopped
    user: "1000:1000"
    security_opts:
      - no-new-privileges:true
      - apparmor:docker-default
    networks:
      - name: public_network
    volumes:
      - "{{ docker_dir }}/n8n/:/home/node/.n8n"
    env:
      GENERIC_TIMEZONE: "Europe/Istanbul"
      TZ: "Europe/Istanbul"
    labels:
      traefik.enable: "true"
      traefik.http.routers.n8n.entrypoints: "https"
      traefik.http.routers.n8n.rule: "Host(`{{ n8n_host }}`)"
      traefik.http.routers.n8n.tls: "true"
      traefik.http.routers.n8n.service: "n8n"
      traefik.http.routers.n8n.middlewares: "secure-vpn-with-auth@file"
      traefik.http.services.n8n.loadbalancer.server.port: "5678"
      