---
- name: Update the packages and configure auto-updates
  ansible.builtin.include_tasks: setup.yml

- name: Configure swap
  ansible.builtin.include_tasks:
    file: swap.yml
    apply:
      become: true
  when: system_swap_enabled

- name: Configure the firewall
  ansible.builtin.include_tasks: firewall.yml

- name: Configure Docker image prune
  ansible.builtin.include_tasks: docker_image_prune.yml
