---
###############################################################
#                   Authelia configuration                    #
###############################################################

identity_validation:
  reset_password:
    jwt_secret: "{{ jwt_secret }}"

ntp:
  disable_failure: true

server:
  address: tcp://0.0.0.0:9091
  endpoints:
    authz:
      forward-auth:
        implementation: "ForwardAuth"

log:
  level: info

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: two_factor
  rules:
    - domain: "{{ authelia_host }}"
      policy: bypass

session:
  secret: "{{ session_secret }}"
  cookies:
    - name: authelia_session
      domain: "{{ root_host }}"
      authelia_url: "https://{{ authelia_host }}"
      default_redirection_url: "https://{{ root_host }}"

  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: "{{ storage_encryption_key }}"
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    address: "submission://{{ email_smtp_host }}:{{ email_smtp_port }}"
    username: "{{ email_login }}"
    password: "{{ email_password }}"
    sender: "Authelia <{{ email_login }}>"
