---
- name: Create Seafile directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0775"
  loop:
    - "{{ docker_dir }}/seafile"
    - "{{ docker_dir }}/seafile/shared"
    - "{{ docker_dir }}/seafile/db"

- name: Create mount point
  ansible.builtin.file:
    path: "{{ seafile_storage_box_mount_path }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0775"
  when: seafile_storage_box_mount_enabled | default(false)

- name: Bind mount seafile data
  ansible.posix.mount:
    src: "{{ storagebox_mount_path }}/seafile"
    path: "{{ seafile_storage_box_mount_path }}"
    opts: bind
    fstype: none
    state: mounted
  when: seafile_storage_box_mount_enabled | default(false)

- name: Copy .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ docker_dir }}/seafile/.env"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Copy seafile-server.yml
  ansible.builtin.template:
    src: seafile-server.yml.j2
    dest: "{{ docker_dir }}/seafile/seafile-server.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0640"

- name: Docker Compose up
  community.docker.docker_compose_v2:
    project_src: "{{ docker_dir }}/seafile"
    files:
      - seafile-server.yml
    state: present
