---
services:
  web:
    image: "docker.io/wger/server:{{ wger_version }}"
    restart: unless-stopped
    env_file:
      - ./config/prod.env
    expose:
      - "8000"
    networks:
      - default
      - reverse_proxy_network
      - postgres_network
      - redis_network
    volumes:
      - static:/home/wger/static
      - media:/home/wger/media
    labels:
      traefik.enable: "true"
      traefik.docker.network: "reverse_proxy_network"
      traefik.http.routers.wger.entrypoints: "https"
      traefik.http.routers.wger.rule: "Host(`{{ wger_host }}`)"
      traefik.http.routers.wger.tls: "true"
      traefik.http.routers.wger.service: "wger"
      traefik.http.routers.wger.middlewares: "secure-vpn-with-auth@file"
      traefik.http.services.wger.loadbalancer.server.port: "8000"

  celery_worker:
    image: "docker.io/wger/server:{{ wger_version }}"
    restart: unless-stopped
    command: /start-worker
    env_file:
      - ./config/prod.env
    networks:
      - default
      - postgres_network
      - redis_network
    volumes:
      - media:/home/wger/media

  celery_beat:
    image: "docker.io/wger/server:{{ wger_version }}"
    restart: unless-stopped
    command: /start-beat
    env_file:
      - ./config/prod.env
    networks:
      - default
      - postgres_network
      - redis_network
    volumes:
      - media:/home/wger/media

volumes:
  static:
  media:

networks:
  reverse_proxy_network:
    external: true
  postgres_network:
    external: true
  redis_network:
    external: true
