---
wger_version: "latest"
wger_redis_version: "latest"

wger_project_dir: "{{ docker_dir }}/wger"
wger_timezone: "Europe/Istanbul"
wger_db_host: "immich_postgres"
wger_db_name: "wger"
wger_db_user: "wger"

# Override this in custom/secret vars for production
wger_db_password: "wger"
wger_secret_key: "change-me-in-secret-yml"
