---
immich_version: "v2.5.6"
immich_postgres_image: "ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23"

# Storage Box mount
immich_storage_box_mount_enabled: true
immich_storage_box_mount_path: "{{ docker_dir }}/immich/external"
immich_storage_box_remote_path: "immich"

# Storage location — points to Storage Box (where photos/videos live)
immich_upload_location: "{{ immich_storage_box_mount_path }}"
