---
# Storage Box mount
immich_storage_box_mount_enabled: true
immich_storage_box_mount_path: "{{ docker_dir }}/immich/external"
immich_storage_box_host: ""
immich_storage_box_port: 22
immich_storage_box_user: ""
immich_storage_box_pass: ""
immich_storage_box_remote_path: "immich"
immich_storage_box_enabled: true

# Storage location (used in .env)
immich_upload_location: "{{ immich_storage_box_mount_path }}"

# Database hostname for Immich API
immich_db_hostname: "{{ postgres_container_name }}"
