---
- name: Create metube downloads directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/metube/downloads"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Create metube cookies directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/metube/cookies"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy the cookies.txt
  ansible.builtin.template:
    src: cookies.txt
    dest: "{{ docker_dir }}/metube/cookies/cookies.txt"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0640

- name: Make sure the metube container is created and running
  community.general.docker_container:
    name: "metube"
    image: "ghcr.io/alexta69/metube:{{ metube_version }}"
    pull: "always"
    state: started
    restart_policy: unless-stopped
    security_opts:
      - no-new-privileges:true
      - apparmor:docker-default
    networks:
      - name: public_network
    volumes:
      - "{{ docker_dir }}/metube/downloads:/downloads"
      - "{{ docker_dir }}/metube/cookies:/cookies"
      - "{{ docker_dir }}/traefik/data/certificates/{{root_host}}:/ssl"
    env:
      YTDL_OPTIONS: '{"cookiefile":"/cookies/cookies.txt"}'
    labels:
      traefik.enable: "true"
      traefik.http.routers.metube.entrypoints: "https"
      traefik.http.routers.metube.rule: "Host(`{{ metube_host }}`) && !Path(`/knock-knock`)"
      traefik.http.routers.metube.tls: "true"
      traefik.http.routers.metube.service: "metube"
      traefik.http.routers.metube.middlewares: "secure-external@file,dynamic-ipwhitelist@file"  
      traefik.http.services.metube.loadbalancer.server.port: "8081" 
      traefik.http.routers.metube-dynamic.tls: "true"
      traefik.http.routers.metube-dynamic.rule: "Host(`{{ metube_host }}`) && PathPrefix(`/knock-knock`)"
      traefik.http.routers.metube-dynamic.service: "traefikshaper"
      traefik.http.services.metube-dynamic.loadbalancer.server.port: "5000"
      
      
